version : '3'
services :
  mongo:
    image: mongo
    restart: always
    network_mode : host
    
  mysql:
    image: mysql
    restart: always
    network_mode : host
    environment:
      MYSQL_ROOT_PASSWORD: Student@123
      MYSQL_USER: root
      MYSQL_PASSWORD: Student@123
      MYSQL_DATABASE: mygithubprojectdb

  netflix-eureka-naming-server:
    image : netflix-eureka-naming-server
    build : netflix-eureka-naming-server
    restart : always
    network_mode : host
    container_name : netflix-eureka-naming-server
    ports :
      - 8761:8761
    depends_on:
      - mongo
    expose:
       - 8761

  netflix-zuul-api-gateway-server:
    image : netflix-zuul-api-gateway-server
    build : netflix-zuul-api-gateway-server
    restart : always
    network_mode : host
    container_name : netflix-zuul-api-gateway-server
    depends_on:
      - mongo
      - netflix-eureka-naming-server
    ports :
      - 8765:8765
    expose:
       - 8765

  spring-cloud-config-server:
    image : spring-cloud-config-server
    build : spring-cloud-config-server
    restart : always
    network_mode : host
    container_name : spring-cloud-config-server
    depends_on:
      - mongo
      - netflix-eureka-naming-server
      - netflix-zuul-api-gateway-server
    ports :
      - 8888:8888
    expose:
       - 8888

  profile-service:
    image : profile-service
    build : profile-service
    restart : always
    network_mode : host
    container_name : profile-service
    depends_on:
      - mongo
      - netflix-eureka-naming-server
      - netflix-zuul-api-gateway-server
      - spring-cloud-config-server
    ports :
      - 8083:8083
    expose:
       - 8083

  authentication-service:
    image : authentication-service
    build : authentication-service
    restart : always
    network_mode : host
    container_name : authentication-service
    depends_on:
      - mongo
      - netflix-eureka-naming-server
      - netflix-zuul-api-gateway-server
      - spring-cloud-config-server
    ports :
      - 8090:8090
    expose:
       - 8090

  comment-service:
    image : comment-service
    build : comment-service
    restart : always
    network_mode : host
    container_name : comment-service
    depends_on:
      - mongo
      - netflix-eureka-naming-server
      - netflix-zuul-api-gateway-server
      - spring-cloud-config-server
      - authentication-service
    ports :
      - 8081:8081
    expose:
       - 8081

  favourite-service:
    image : favourite-service
    build : favourite-service
    restart : always
    network_mode : host
    container_name : favourite-service
    depends_on:
      - mongo
      - netflix-eureka-naming-server
      - netflix-zuul-api-gateway-server
      - spring-cloud-config-server
      - authentication-service
    ports :
      - 8082:8082
    expose:
       - 8082